---
title: "R Notebook"
output: html_notebook
---


### Importe de Bibliotecas

```{r}
library(ggplot2)
```


### Importe Datos

```{r}
#tiemposBusquedaVecino <- read.csv("datos/timeResults.csv",sep = ";") #tiempos.csv
tiempoCompresion <- read.csv("datos/compresion.csv",sep = ";")
tiemposBusquedaVecino <- read.csv("datos/timeNano.csv", sep = ";")
```

### Trabajo datos

```{r}
options(scipen = 999)
tiempoCompresion$VariacionTiempo = tiempoCompresion$TiempoFin - tiempoCompresion$TiempoInicio
```

### Gráfico tiemposBusquedaVecino

```{r}
ggplot(tiemposBusquedaVecino, aes(x=SetDatos, y=Tiempos, color=Estructura)) + # fill=Estructura

  geom_boxplot() +

  labs(title= "Tiempos de búsqueda de vecinos (10000 datos)",
       color = "Estructura del Grafo",
       y = "Tiempo [ns] (log10)",
       x = "Set de datos") +

  theme(plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(trans='log10', breaks = c(1,10,100,1000,10000,100000, 1000000, 10000000, 100000000, 1000000000))
# c(1000, 1000000, 1000000000)

ggsave(plot = last_plot(), filename = "searchTime.jpeg")
ggsave(plot = last_plot(), filename = "searchTime.pdf")
```


### 
```{r}
tiemposBusquedaVecinoFiltrado <- subset(tiemposBusquedaVecino,
                                        Estructura %in% c("graphCompDense","graphComp","graphNativeFullDense","graphNativeFull"))
```

```{r}

ggplot(tiemposBusquedaVecinoFiltrado, aes(x=SetDatos, y=Tiempos, color=Estructura)) + # fill=Estructura

  geom_boxplot() +

  labs(title= "Tiempos de búsqueda de vecinos (10000 datos)",
       color = "Estructura del Grafo",
       y = "Tiempo [ns] (log10)",
       x = "Set de datos") +

  theme(plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(trans='log10', breaks = c(1,10,100,1000,10000,100000, 1000000, 10000000, 100000000, 1000000000))

ggsave(plot = last_plot(), filename = "searchTime2.jpeg")
ggsave(plot = last_plot(), filename = "searchTime2.pdf")
```
```


### Gráfico tiempoCompresión

```{r}
 ggplot(tiempoCompresion, aes(x=LineasArchivo, y=VariacionTiempo, group=1)) + geom_line()
```

