---
title: "R Notebook"
output: html_notebook
---


### Importe de Bibliotecas

```{r}
library(ggplot2)
```

## Tiempo de Búsqueda de caminos

### Importe Datos

```{r}
tiemposBusquedaCamino <- read.csv("datos/TPF_OptMem_lim-1.csv", sep = ";")
tiemposBusquedaCamino_1000 <- read.csv("datos/TPF_OptMem_lim1000.csv", sep = ";")
tiemposBusquedaCamino_10000 <- read.csv("datos/TPF_OptMem_lim10000.csv", sep = ";")
tiemposBusquedaCamino_100000 <- read.csv("datos/TPF_OptMem_lim100000.csv", sep = ";")
tiemposBusquedaCamino_1000000 <- read.csv("datos/TPF_OptMem_lim1000000.csv", sep = ";")

tiemposBusquedaCamino_limExc <- read.csv("datos/OptMemLimExc/out.csv", sep = ";")
```

### Edita datos

```{r}
options(scipen = 999)


all_data = rbind(tiemposBusquedaCamino,tiemposBusquedaCamino_1000,tiemposBusquedaCamino_10000,tiemposBusquedaCamino_100000,tiemposBusquedaCamino_1000000)

all_data$Limite = as.character(all_data$Limite)
all_data$Limite[all_data$Limite == "-1"] <- "Sin límite"
tiemposBusquedaCamino_limExc$Limite = as.character(tiemposBusquedaCamino_limExc$Limite)
tiemposBusquedaCamino_limExc$Limite[tiemposBusquedaCamino_limExc$Limite == "-1"] <- "Sin límite"

all_data$Grupos[all_data$Grupos == "penta"] <- "5"
all_data$Grupos[all_data$Grupos == "cuadra"] <- "4"
all_data$Grupos[all_data$Grupos == "triple"] <- "3"
all_data$Grupos[all_data$Grupos == "double"] <- "2"
tiemposBusquedaCamino_limExc$Grupos[tiemposBusquedaCamino_limExc$Grupos == "penta"] <- "5"
tiemposBusquedaCamino_limExc$Grupos[tiemposBusquedaCamino_limExc$Grupos == "cuadra"] <- "4"
tiemposBusquedaCamino_limExc$Grupos[tiemposBusquedaCamino_limExc$Grupos == "triple"] <- "3"
tiemposBusquedaCamino_limExc$Grupos[tiemposBusquedaCamino_limExc$Grupos == "double"] <- "2"

all_data$grupos_id = paste(all_data$Grupos,"_", as.character(all_data$ID))
ids_aristas_cero <- all_data$grupos_id[all_data$Aristas == 0]
tiemposBusquedaCamino_limExc$grupos_id = paste(tiemposBusquedaCamino_limExc$Grupos,"_", as.character(tiemposBusquedaCamino_limExc$ID))
ids_aristas_cero_limExc <- tiemposBusquedaCamino_limExc$grupos_id[tiemposBusquedaCamino_limExc$Aristas == 0]

all_data_SAC <- all_data[!
    (all_data$grupos_id %in% ids_aristas_cero), ]
all_data_SAC$memArista = all_data_SAC$Memoria / all_data_SAC$Aristas
tiemposBusquedaCamino_limExc_SAC <- tiemposBusquedaCamino_limExc[!
    (tiemposBusquedaCamino_limExc$grupos_id %in% ids_aristas_cero), ]
tiemposBusquedaCamino_limExc_SAC$memArista = tiemposBusquedaCamino_limExc_SAC$Memoria / tiemposBusquedaCamino_limExc_SAC$Aristas
```

```{r}
# Valores Nuevos
ids_aristas_cero[!(ids_aristas_cero %in% ids_aristas_cero_limExc)]

```

### Gráfico

```{r}
ggplot(all_data, aes(x=Grupos, y=Aristas,color = Limite)) + 
  geom_boxplot() + 
  labs(title= "Aristas encontradas 60 segundos",
       color = "Límite de Aristas",
       y = "Aristas encontradas (log10)",
       x = "Cantidad de Entidades") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(trans='log10', breaks = c(10^0,10^1,10^2,10^3,10^4,10^5,10^6,10^7,10^8,10^9,10^10,10^11))

ggsave(plot = last_plot(), filename = "export/4_LimitesAristas.png", width=8, height=5, dpi=300)
ggsave(plot = last_plot(), filename = "export/4_LimitesAristas.pdf", width=8, height=5, dpi=300)
```

```{r}
ggplot(tiemposBusquedaCamino_limExc, aes(x=Grupos, y=Aristas,color = Limite)) + 
  geom_boxplot() + 
  labs(title= "Aristas encontradas 60 segundos",
       color = "Límite de Aristas",
       y = "Aristas encontradas (log10)",
       x = "Cantidad de Entidades") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(trans='log10', breaks = c(10^0,10^1,10^2,10^3,10^4,10^5,10^6,10^7,10^8,10^9,10^10,10^11))

ggsave(plot = last_plot(), filename = "export/4_LimitesAristasExc.png", width=8, height=5, dpi=300)
ggsave(plot = last_plot(), filename = "export/4_LimitesAristasExc.pdf", width=8, height=5, dpi=300)
```

```{r}
ggplot(all_data, aes(x=Grupos, y=Memoria,color = Limite)) + 
  geom_boxplot() +
  labs(title= "Uso de memoria búsqueda 60 segundos",
       color = "Límite de Aristas",
       y = "Memoria [bytes]",
       x = "Cantidad de Entidades") +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(vars(Limite))  + 
  scale_y_continuous(trans='log10', breaks = c(10^0,10^1,10^2,10^3,10^4,10^5,10^6,10^7,10^8,10^9,10^10,10^11,10^12))

ggsave(plot = last_plot(), filename = "export/4_LimitesMemoria.png", width=8, height=5, dpi=300)
ggsave(plot = last_plot(), filename = "export/4_LimitesMemoria.pdf", width=8, height=5, dpi=300)
```

```{r}
ggplot(tiemposBusquedaCamino_limExc, aes(x=Grupos, y=Memoria,color = Limite)) + 
  geom_boxplot() +
  labs(title= "Uso de memoria búsqueda 60 segundos",
       color = "Límite de Aristas",
       y = "Memoria [bytes]",
       x = "Cantidad de Entidades") +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(vars(Limite))  + 
  scale_y_continuous(trans='log10', breaks = c(10^0,10^1,10^2,10^3,10^4,10^5,10^6,10^7,10^8,10^9,10^10,10^11,10^12))

ggsave(plot = last_plot(), filename = "export/4_LimitesMemoriaExc.png", width=8, height=5, dpi=300)
ggsave(plot = last_plot(), filename = "export/4_LimitesMemoriaExc.pdf", width=8, height=5, dpi=300)
```

```{r}
ggplot(all_data_SAC, aes(x=Grupos, y=memArista,color = Limite)) + 
  geom_boxplot() +
  labs(title= "Proporción memoria/cantidad de aristas, en búsqueda 60 segundos",
       color = "Límite de Aristas",
       y = "Memoria/Cantidad de Aristas [bytes]",
       x = "Cantidad de Entidades") +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(vars(Limite))  + 
  scale_y_continuous(trans='log10', breaks = c(10^0,10^1,10^2,10^3,10^4,10^5,10^6,10^7,10^8,10^9,10^10,10^11,10^12))

ggsave(plot = last_plot(), filename = "export/4_LimitesMemoriaAristas.png", width=8, height=5, dpi=300)
ggsave(plot = last_plot(), filename = "export/4_LimitesMemoriaAristas.pdf", width=8, height=5, dpi=300)
```


```{r}
ggplot(tiemposBusquedaCamino_limExc_SAC, aes(x=Grupos, y=memArista,color = Limite)) + 
  geom_boxplot() +
  labs(title= "Proporción memoria/cantidad de aristas, en búsqueda 60 segundos",
       color = "Límite de Aristas",
       y = "Memoria/Cantidad de Aristas [bytes]",
       x = "Cantidad de Entidades") +
  theme(plot.title = element_text(hjust = 0.5)) +
  #facet_grid(vars(Limite))  + 
  scale_y_continuous(trans='log10', breaks = c(10^0,10^1,10^2,10^3,10^4,10^5,10^6,10^7,10^8,10^9,10^10,10^11,10^12))

ggsave(plot = last_plot(), filename = "export/4_LimitesMemoriaAristasExc.png", width=8, height=5, dpi=300)
ggsave(plot = last_plot(), filename = "export/4_LimitesMemoriaAristasExc.pdf", width=8, height=5, dpi=300)
```