---
title: "R Notebook"
output: html_notebook
---


### Importe de Bibliotecas

```{r}
library(ggplot2)
```

## Tiempo de Búsqueda de vecinos

### Importe Datos

```{r}
tiemposBusquedaVecino <- read.csv("datos/timeNano.csv", sep = ";")
```

### Trabajo datos

```{r}
options(scipen = 999)
tiemposBusquedaVecino$Estructura[tiemposBusquedaVecino$Estructura == "graphGt"] <- "Objetos de Java"
tiemposBusquedaVecino$Estructura[tiemposBusquedaVecino$Estructura == "graphComp"] <- "Comprimido con índices"
tiemposBusquedaVecino$Estructura[tiemposBusquedaVecino$Estructura == "graphCompDense"] <- "Comprimido"
tiemposBusquedaVecino$Estructura[tiemposBusquedaVecino$Estructura == "graphNativeFull"] <- "Arreglos nativos con índices"
tiemposBusquedaVecino$Estructura[tiemposBusquedaVecino$Estructura == "graphNativeFullDense"] <- "Arreglos nativos"

tiemposBusquedaVecino = tiemposBusquedaVecino[tiemposBusquedaVecino$Estructura !='graphNative',]
```

### Gráfico tiemposBusquedaVecino

```{r}
ggplot(tiemposBusquedaVecino, aes(x=SetDatos, y=Tiempos, color=Estructura)) + # fill=Estructura

  geom_boxplot() +

  labs(title= "Tiempos de búsqueda de vecinos",
       color = "Estructura del Grafo",
       y = "Tiempo [ns] (log10)",
       x = "Set de datos") +

  theme(plot.title = element_text(hjust = 0.5)) +
  #+ theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
  scale_y_continuous(trans='log10', breaks = c(1,10,100,1000,10000,100000, 1000000, 10000000, 100000000, 1000000000, 10000000000, 100000000000, 1000000000000))
# c(1000, 1000000, 1000000000)

#ggsave(plot = last_plot(), filename = "export/4_TiempoBusquedaVecinos.png", width=8, height=5, #dpi=300)
#ggsave(plot = last_plot(), filename = "export/4_TiempoBusquedaVecinos.pdf", width=8, height=5, #dpi=300)
# width=4, height=4, dpi=300
```

